### ISSUE TITLE
ImportError: No module named flops_benchmark

### ISSUE THREAD

**Issue by veepersgit** [Lan1991Xu/ONE_NeurIPS2018#1]
Traceback (most recent call last):
  File "cifar_one.py", line 24, in <module>
    from utils import Bar, Logger, AverageMeter, accuracy, mkdir_p, savefig,ramps
  File "/home/mc/ONE_NeurIPS2018/utils/__init__.py", line 8, in <module>
    from .flops_benchmark import *
ImportError: No module named flops_benchmark
--------------------------------------------------------------------------------------------------------------
Couldn't find any file under the directory utils, Pls check.

**Comment by Lan1991Xu** [comment]
Fixed. 
comment from .flops_benchmark import *
