### ISSUE TITLE
Ask about the python verion

### ISSUE THREAD

**Issue by littlesnowperfume** [Lan1991Xu/ONE_NeurIPS2018#4]
I saw your code (cifar basiline .py) and find out that line 109
    print('==> Preparing dataset %s' % args.dataset)
It seems that you use python 3.X not python 2.7 , maybe you need to change the information in your READ.ME

**Comment by Lan1991Xu** [comment]
Hi, thanks for your feedback. We use python2.7, any errors when you run on this environment?
